//----------------------
// <auto-generated>
//    請勿修改此檔案內容，以免產生不可預期的錯誤。
//    產生日期:2024-03-22 06:28:28。
//    類別:Justin, 表單:外部起單-所有欄位, 版本:3
//     Generated using the NJsonSchema v10.9.0.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------


namespace Ede.Uofx.FormSchema.UofxFormSchema
{
    #pragma warning disable // Disable all warnings

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.9.0.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class FileItem
    {
        /// <summary>
        /// Id
        /// </summary>
        [Newtonsoft.Json.JsonProperty("Id", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required]
        public System.Guid Id { get; set; }

        /// <summary>
        /// Name
        /// </summary>
        [Newtonsoft.Json.JsonProperty("FileName", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required]
        public string FileName { get; set; }
    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.9.0.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class UofxFormSchemaFields
    {
        /// <summary>
        /// 單行文字
        /// </summary>
        [Newtonsoft.Json.JsonProperty("C002", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [System.ComponentModel.DataAnnotations.StringLength(255)]
        public string C002 { get; set; }

        /// <summary>
        /// 多行文字
        /// </summary>
        [Newtonsoft.Json.JsonProperty("C003", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string C003 { get; set; }

        /// <summary>
        /// 數值欄位
        /// </summary>
        [Newtonsoft.Json.JsonProperty("C004", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [System.ComponentModel.DataAnnotations.Range(1.0D, 200.0D)]
        public decimal? C004 { get; set; }

        /// <summary>
        /// 任意選
        /// </summary>
        [Newtonsoft.Json.JsonProperty("C020", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.Collections.Generic.ICollection<AllOrgItem> C020 { get; set; }

        /// <summary>
        /// 日期
        /// </summary>
        [Newtonsoft.Json.JsonProperty("C005", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.DateTimeOffset? C005 { get; set; }

        /// <summary>
        /// 日期時間
        /// </summary>
        [Newtonsoft.Json.JsonProperty("C006", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.DateTimeOffset? C006 { get; set; }

        /// <summary>
        /// 複選清單，複選項目: 選項1、選項2、其他-{你的說明}
        /// </summary>
        [Newtonsoft.Json.JsonProperty("C007", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.Collections.Generic.ICollection<string> C007 { get; set; }

        /// <summary>
        /// 單選清單，單選項目: 選項1、選項2、其他-{你的說明}
        /// </summary>
        [Newtonsoft.Json.JsonProperty("C008", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string C008 { get; set; }

        /// <summary>
        /// 下拉選單，選單項目: 選項1、選項2
        /// </summary>
        [Newtonsoft.Json.JsonProperty("C009", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string C009 { get; set; }

        /// <summary>
        /// 文字編輯
        /// </summary>
        [Newtonsoft.Json.JsonProperty("C011", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string C011 { get; set; }

        /// <summary>
        /// 上傳檔案
        /// </summary>
        [Newtonsoft.Json.JsonProperty("C017", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.Collections.Generic.ICollection<FileItem> C017 { get; set; }

        /// <summary>
        /// 選擇部門
        /// </summary>
        [Newtonsoft.Json.JsonProperty("C018", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.Collections.Generic.ICollection<DeptItem> C018 { get; set; }

        /// <summary>
        /// 選擇人員
        /// </summary>
        [Newtonsoft.Json.JsonProperty("C019", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.Collections.Generic.ICollection<AccountItem> C019 { get; set; }

        /// <summary>
        /// 明細欄位
        /// </summary>
        [Newtonsoft.Json.JsonProperty("C023", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.Collections.Generic.ICollection<C023Row> C023 { get; set; }


    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.9.0.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class AllOrgItem
    {
        /// <summary>
        /// 類型
        /// </summary>
        [Newtonsoft.Json.JsonProperty("ItemType", Required = Newtonsoft.Json.Required.Always)]
        public UserSetItemType ItemType { get; set; }

        /// <summary>
        /// 部門
        /// </summary>
        [Newtonsoft.Json.JsonProperty("Dept", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public DeptItem Dept { get; set; }

        /// <summary>
        /// 員工
        /// </summary>
        [Newtonsoft.Json.JsonProperty("Employee", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public AccountItem Employee { get; set; }

        /// <summary>
        /// JobTitleCode
        /// </summary>
        [Newtonsoft.Json.JsonProperty("JobTitleCode", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string JobTitleCode { get; set; }

        /// <summary>
        /// JobFuncCode
        /// </summary>
        [Newtonsoft.Json.JsonProperty("JobFuncCode", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string JobFuncCode { get; set; }

        /// <summary>
        /// 部門代碼
        /// </summary>
        [Newtonsoft.Json.JsonProperty("DeptSupervisor", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string DeptSupervisor { get; set; }


    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.9.0.0 (Newtonsoft.Json v13.0.0.0)")]
    public enum UserSetItemType
    {

        Employee = 0,


        Department = 1,


        JobTitle = 2,


        JobFunction = 3,


        DeptJobTitle = 4,


        DeptJobFunc = 5,


        DeptSupervisor = 6,


        DeptEmployee = 7,


    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.9.0.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class DeptItem
    {
        /// <summary>
        /// 部門代碼
        /// </summary>
        [Newtonsoft.Json.JsonProperty("Code", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required]
        public string Code { get; set; }

        /// <summary>
        /// 是否包含子部門
        /// </summary>
        [Newtonsoft.Json.JsonProperty("ContainsChildren", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public bool ContainsChildren { get; set; }


    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.9.0.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class AccountItem
    {
        /// <summary>
        /// 申請者原公司代碼(如為其他公司兼職才需要填)
        /// </summary>
        [Newtonsoft.Json.JsonProperty("CorpCode", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string CorpCode { get; set; }

        /// <summary>
        /// 部門代碼，此人員所屬的部門
        /// </summary>
        [Newtonsoft.Json.JsonProperty("DeptCode", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required]
        public string DeptCode { get; set; }

        /// <summary>
        /// 人員帳號
        /// </summary>
        [Newtonsoft.Json.JsonProperty("Account", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required]
        public string Account { get; set; }


    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.9.0.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class C023Row
    {
        /// <summary>
        /// 單行文字
        /// </summary>
        [Newtonsoft.Json.JsonProperty("C024", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [System.ComponentModel.DataAnnotations.StringLength(255)]
        public string C024 { get; set; }

        /// <summary>
        /// 數值欄位
        /// </summary>
        [Newtonsoft.Json.JsonProperty("C025", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [System.ComponentModel.DataAnnotations.Range(1, 999)]
        public int? C025 { get; set; }

        /// <summary>
        /// 上傳檔案
        /// </summary>
        [Newtonsoft.Json.JsonProperty("C026", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.Collections.Generic.ICollection<FileItem> C026 { get; set; }


    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.9.0.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class UofxFormSchema
    {
        /// <summary>
        /// 請勿修改
        /// </summary>
        [Newtonsoft.Json.JsonProperty("FormId", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required]
        public System.Guid FormId { get; set; } = new System.Guid("6a64ae26-c805-4597-17f3-08da41eeef8e");

        /// <summary>
        /// 請勿修改
        /// </summary>
        [Newtonsoft.Json.JsonProperty("ScriptId", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required]
        public System.Guid ScriptId { get; set; } = new System.Guid("3a9642d0-b3bb-4fee-cf43-08da58d3380a");

        /// <summary>
        /// 人員帳號
        /// </summary>
        [Newtonsoft.Json.JsonProperty("Account", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required]
        public string Account { get; set; }

        /// <summary>
        /// 申請者原公司代碼(如為其他公司兼職才需要填)
        /// </summary>
        [Newtonsoft.Json.JsonProperty("CorpCode", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string CorpCode { get; set; }

        /// <summary>
        /// 部門代碼，此人員所屬的部門
        /// </summary>
        [Newtonsoft.Json.JsonProperty("DeptCode", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required]
        public string DeptCode { get; set; }

        /// <summary>
        /// 起單完成要回覆的 api url
        /// </summary>
        [Newtonsoft.Json.JsonProperty("CallBackUrl", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string CallBackUrl { get; set; }

        /// <summary>
        /// 使用者自訂資料，會在 CallBack 時回傳
        /// </summary>
        [Newtonsoft.Json.JsonProperty("CustomData", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string CustomData { get; set; }

        /// <summary>
        /// 急件
        /// </summary>
        [Newtonsoft.Json.JsonProperty("Urgent", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public bool Urgent { get; set; }

        /// <summary>
        /// 備註說明
        /// </summary>
        [Newtonsoft.Json.JsonProperty("Opinion", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string Opinion { get; set; }

        /// <summary>
        /// 附件。請先呼叫檔案上傳 (UofxService.File.FileUpload) 取得 id 和 name
        /// </summary>
        [Newtonsoft.Json.JsonProperty("AttachFiles", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.Collections.Generic.ICollection<FileItem> AttachFiles { get; set; }

        /// <summary>
        /// 表單欄位
        /// </summary>
        [Newtonsoft.Json.JsonProperty("Fields", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required]
        public UofxFormSchemaFields Fields { get; set; } = new UofxFormSchemaFields();


    }
}